TRUNCATE TABLE [Patient]
GO
INSERT [dbo].[Patient] ([FirstName], [LastName], [Age], [StatusTypeId], [AdmissionDate], [DischargeDate], [PhysicianId]) 
VALUES 
(N'Betty',N'Walker', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Kimberly',N'Green', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'William',N'Phillips', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Donald',N'Davis', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Jeff',N'Martin', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Elizabeth',N'Hall', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Helen',N'Adams', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Deborah',N'Campbell', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'David',N'Miller', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'George',N'Thompson', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Jennifer',N'Allen', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Sandra',N'Baker', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Richard',N'Parker', floor(10 + RAND() * 89), 2, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Kenneth',N'Wilson', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Maria',N'Garcia', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Donna',N'Young', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Charles',N'Gonzalez', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Steven',N'Evans', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Susan',N'Moore', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Carol',N'Martinez', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Joseph',N'Hernandez', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Edward',N'Nelson', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Margaret',N'Edwards', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Ruth',N'Taylor', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Thomas',N'Robinson', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Brian',N'King', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Dorothy',N'Carter', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Paul', N'Hill', floor(10 + RAND() * 89), 1, GETDATE(), GETDATE(), CAST(RAND() * 9 + 1 as INT)),
(N'Kevin', N'Roberts', floor(10 + RAND() * 89), 1, GETDATE(), DATEADD(mi, 10,   GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Linda', N'Jones', floor(10 + RAND() * 89), 1, GETDATE(), DATEADD(mi, 10,   GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Karen', N'White', floor(10 + RAND() * 89), 1, GETDATE(), DATEADD(mi, 10,   GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Sarah', N'Lee', floor(10 + RAND() * 89), 1, GETDATE(), DATEADD(mi, 10,   GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Michael', N'Scott', floor(10 + RAND() * 89), 1, GETDATE(), DATEADD(mi, 10,   GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Mark', N'Turner', floor(10 + RAND() * 89), 1, GETDATE(), DATEADD(mi, 10,   GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Jason', N'Brown', floor(10 + RAND() * 89), 1, GETDATE(), DATEADD(mi, 10,   GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'Barbara', N'Harris', floor(10 + RAND() * 89), 1, GETDATE(), DATEADD(mi, 10,   GETDATE()), CAST(RAND() * 9 + 1 as INT)),
(N'TestF11', N'TestL11', floor(10 + RAND() * 89), 1, GETDATE(), null, 1),
(N'TestF12', N'TestL12', floor(10 + RAND() * 89), 1, GETDATE(), null, 1),
(N'TestF13', N'TestL13', floor(10 + RAND() * 89), 1, GETDATE(), null, 1),
(N'TestF14', N'TestL14', floor(10 + RAND() * 89), 1, GETDATE(), null, 1),
(N'TestF15', N'TestL15', floor(10 + RAND() * 89), 1, GETDATE(), null, 1),
(N'TestF16', N'TestL16', floor(10 + RAND() * 89), 1, GETDATE(), null, 2),
(N'TestF17', N'TestL17', floor(10 + RAND() * 89), 1, GETDATE(), null, 2),
(N'TestF18', N'TestL18', floor(10 + RAND() * 89), 1, GETDATE(), null, 2),
(N'TestF19', N'TestL19', floor(10 + RAND() * 89), 1, GETDATE(), null, 2),
(N'TestF10', N'TestL10', floor(10 + RAND() * 89), 1, GETDATE(), null, 2),
(N'TestF21', N'TestL21', floor(10 + RAND() * 89), 1, GETDATE(), null, 2),
(N'TestF22', N'TestL22', floor(10 + RAND() * 89), 1, GETDATE(), null, 3),
(N'TestF23', N'TestL23', floor(10 + RAND() * 89), 1, GETDATE(), null, 3),
(N'TestF24', N'TestL24', floor(10 + RAND() * 89), 1, GETDATE(), null, 3),
(N'TestF25', N'TestL25', floor(10 + RAND() * 89), 1, GETDATE(), null, 3),
(N'TestF26', N'TestL26', floor(10 + RAND() * 89), 1, GETDATE(), null, 3),
(N'TestF27', N'TestL27', floor(10 + RAND() * 89), 1, GETDATE(), null, 3),
(N'TestF28', N'TestL28', floor(10 + RAND() * 89), 1, GETDATE(), null, 4),
(N'TestF29', N'TestL29', floor(10 + RAND() * 89), 1, GETDATE(), null, 4),
(N'TestF20', N'TestL20', floor(10 + RAND() * 89), 1, GETDATE(), null, 4),
(N'TestF31', N'TestL31', floor(10 + RAND() * 89), 1, GETDATE(), null, 4),
(N'TestF32', N'TestL32', floor(10 + RAND() * 89), 1, GETDATE(), null, 4),
(N'TestF33', N'TestL33', floor(10 + RAND() * 89), 1, GETDATE(), null, 4),
(N'TestF34', N'TestL34', floor(10 + RAND() * 89), 1, GETDATE(), null, 4),
(N'TestF35', N'TestL35', floor(10 + RAND() * 89), 1, GETDATE(), null, 4),
(N'TestF36', N'TestL36', floor(10 + RAND() * 89), 1, GETDATE(), null, 5),
(N'TestF37', N'TestL37', floor(10 + RAND() * 89), 1, GETDATE(), null, 5),
(N'TestF38', N'TestL38', floor(10 + RAND() * 89), 1, GETDATE(), null, 5),
(N'TestF39', N'TestL39', floor(10 + RAND() * 89), 1, GETDATE(), null, 5),
(N'TestF30', N'TestL30', floor(10 + RAND() * 89), 1, GETDATE(), null, 5),
(N'TestF41', N'TestL41', floor(10 + RAND() * 89), 1, GETDATE(), null, 6),
(N'TestF42', N'TestL42', floor(10 + RAND() * 89), 1, GETDATE(), null, 6),
(N'TestF43', N'TestL43', floor(10 + RAND() * 89), 1, GETDATE(), null, 6),
(N'TestF44', N'TestL44', floor(10 + RAND() * 89), 1, GETDATE(), null, 6),
(N'TestF45', N'TestL45', floor(10 + RAND() * 89), 1, GETDATE(), null, 6),
(N'TestF46', N'TestL46', floor(10 + RAND() * 89), 1, GETDATE(), null, 7),
(N'TestF47', N'TestL47', floor(10 + RAND() * 89), 1, GETDATE(), null, 7),
(N'TestF48', N'TestL48', floor(10 + RAND() * 89), 1, GETDATE(), null, 7),
(N'TestF49', N'TestL49', floor(10 + RAND() * 89), 1, GETDATE(), null, 7),
(N'TestF40', N'TestL40', floor(10 + RAND() * 89), 1, GETDATE(), null, 8),
(N'TestF51', N'TestL51', floor(10 + RAND() * 89), 1, GETDATE(), null, 8),
(N'TestF52', N'TestL52', floor(10 + RAND() * 89), 1, GETDATE(), null, 8),
(N'TestF53', N'TestL53', floor(10 + RAND() * 89), 1, GETDATE(), null, 8),
(N'TestF54', N'TestL54', floor(10 + RAND() * 89), 1, GETDATE(), null, 9),
(N'TestF55', N'TestL55', floor(10 + RAND() * 89), 1, GETDATE(), null, 9),
(N'TestF56', N'TestL56', floor(10 + RAND() * 89), 1, GETDATE(), null, 9),
(N'TestF57', N'TestL57', floor(10 + RAND() * 89), 1, GETDATE(), null, 9),
(N'TestF58', N'TestL58', floor(10 + RAND() * 89), 1, GETDATE(), null, 1),
(N'TestF59', N'TestL59', floor(10 + RAND() * 89), 1, GETDATE(), null, 1),
(N'Sharon',N'Collins', floor(10 + RAND() * 89), 1, DATEADD(MM, -1, GETDATE()), DATEADD(MM, -1, GETDATE()), CAST(RAND() * 9 + 1 as INT))
GO